name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  foundry-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build contracts
        run: forge build

      - name: Check gas consumption
        run: forge snapshot --check --fork-url ${{ secrets.ALCHEMY_MAINNET_RPC }}

      - name: Run tests
        run: forge test -vvv --fork-url ${{ secrets.ALCHEMY_MAINNET_RPC }} --gas-report

  frontend-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        working-directory: ./frontend
        run: npm install
      
      - name: Build
        working-directory: ./frontend
        run: npm run build
        env:
          CI: true

      - name: Tests
        working-directory: ./frontend
        run: npm run test -- --coverage
        env:
          CI: true
